### PR TITLE
Add menuAttributes to fix #361

### LINKED ISSUE #361: Failing AXE tests
I used the tool [axe](https://github.com/dequelabs/axe-core) to scan this autocomplete and got the following errors. 

```
    Expected page to pass Axe accessibility tests.
    Violations found:
    Rule: "aria-input-field-name" (ARIA input fields have an accessible name)
    Help: https://dequeuniversity.com/rules/axe/3.3/aria-input-field-name?application=axe-puppeteer
    Affected Nodes:
      #amp-stories-font-family-picker-1__listbox
        Fix ANY of the following:
        - aria-label attribute does not exist or is empty
        - aria-labelledby attribute does not exist, references elements that do not exist or references elements that are empty
        - Element has no title attribute or the title attribute is empty
    
    Rule: "aria-required-children" (Certain ARIA roles must contain particular children)
    Help: https://dequeuniversity.com/rules/axe/3.3/aria-required-children?application=axe-puppeteer
    Affected Nodes:
      #amp-stories-font-family-picker-1__listbox
        Fix ANY of the following:
        - Required ARIA child role not present: option
```

### PR DESCRIPTION
**Pull request by mchughbri**
Add the `menuAttributes` option to allow for attributes and their values to be added to the `menu` part of the component.

This fixes #361 as it allows for `aria-labelledby` to be set to the `id` of the existing label which in turn allows the code to pass the AXE rule "aria-input-field-name" (ARIA input fields have an accessible name).

No new tests have been added yet. While this PR adds the ability to add `aria-label` or `aria-labelledby`, by default these are not set, and so the default examples on the demo pages will still not pass the aXe tests. 

What do you think we should do about this?

- Set a default `aria-label` value (But what would it say by default?)
- Forcibly set an `id` on the `label` and use `aria-labelledby` to associate the two
- Update all the examples to include manually setting an `aria-label`

### CODE REVIEW

**Comment by romaricpascal** [comment]
Thanks for this update @mchughbri (and your patience with us finding the time to review it 😬 ). The code update is looking good 🙌🏻 

For the examples, it would be neat to update them now we have that new option. I think having an `id` and using `aria-labelledby` would nudge people towards the use intended for `menuAttributes`, so that would be my prefered way to go. If you have a moment to update them and add a little testing for the new option, that'd be ace! Thanks 😄

**Comment by mchughbri** [comment]
Updated examples and added test for the new `menuAttributes` option

**Comment by mchughbri** [comment]
@romaricpascal now done thanks.

**Comment by romaricpascal** [comment]
Oh sorry for my unclear instructions, I meant a force push with a different commit hash to try and trigger whatever Github's do to relaunch the checks.

I usually `git commit --amend -C HEAD` which should generate a new hash for the last commit while keeping everything the same 😊

**Comment by mchughbri** [comment]
All done @romaricpascal thanks.

**Review by romaricpascal — APPROVED** [review]
Cheers! Tests are all green. Just needs a second approval and it'll be good to merge 😊

**Comment by mchughbri** [comment]
Hey @romaricpascal just wondered if we were any closer to getting another approval on this? Thanks.

**Review by owenatgov — APPROVED** [review]

**Comment by owenatgov** [comment]
@mchughbri Sorry for the second delay on this! Looking good, merged :)

**Pull request merged**
