### PR TITLE
Update all the packages

### PR DESCRIPTION
**Pull request by colinrotherham**
I noticed there were lots of out of date packages.

Some of them begin to address issues too:

**1. Automatic polyfills using `@babel/preset-env`**
Babel v7 can now use Browserlist, I've matched GOV.UK Frontend

**2. UglifyJS 3 with IE8 friendly config**
Follows advice from @nickcolley in https://github.com/alphagov/accessible-autocomplete/issues/306

Due to Preact and Webpack we still have issues that IE8 can't overcome, but it's at least possible to debug where the problem lies now.

**3. Karma now uses Istanbul for coverage**
Babel now adds instrumentation with `NODE_ENV=test`, removed deprecated isparta loader

Apart from a flaky IE11 test run (Selenium WebDriver driver error, worked second time) all the SauceLabs tests run perfectly. Even Chrome v70 passes (marked red on the repo home page).

test runs

### CODE REVIEW

**Comment by colinrotherham** [comment]
This pull request builds on top of https://github.com/alphagov/accessible-autocomplete/pull/310 and https://github.com/alphagov/accessible-autocomplete/pull/315 so they'll need merging first.

**Comment by colinrotherham** [comment]
Also swapping PhantomJS (deprecated) with Chrome headless via Puppeteer

**Comment by colinrotherham** [comment]
Hi @nickcolley I did yeah, as it needed the Node.js LTS commit to build properly.

It's rebased now, so those commits are gone now they're merged to master 😊

**Comment by nickcolley** [comment]
I'm surprised Karma is passing, it looks like `onFocusOut` replaced `onBlur`: https://github.com/alphagov/accessible-autocomplete/commit/79b301edf59d9103208aebaa568e0720b195bbb7

**Comment by colinrotherham** [comment]
@nickcolley That's interesting. Unless the tests don't cover this?

I added `onMouseLeave` to the parent `<ul>` to fix other IE issues in an earlier commit, this might have fixed it for combined keyboard + mouse focus handling? https://github.com/alphagov/accessible-autocomplete/blob/f31a4bf5812d75402d4e621f587bf25ea1b9177e/src/autocomplete.js#L491

But then it looks like React's `onBlur` does bubble?
https://github.com/facebook/react/issues/6410#issuecomment-207064994

**Comment by nickcolley** [comment]
I'm hoping this is something that is fixed in the newer React versions but I'm trying to figure out how best to test this.

**Comment by nickcolley** [comment]
This is the bug that was fixed, I'm checking in IE10 right now... https://github.com/alphagov/accessible-autocomplete/issues/193

**Comment by nickcolley** [comment]
I can't reproduce the issue that meant onBlur was changed to onFocusOut, I'm not entire sure why it is no longer an issue.

**Comment by colinrotherham** [comment]
@nickcolley Could you apply the `onBlur` change on top of this and try in IE10?
https://github.com/alphagov/accessible-autocomplete/pull/310

That lacks the Preact update, but does have the timeout on the list closing.

**Comment by nickcolley** [comment]
Alright I think we can safely change that back since you changed the blur behaviour in the pull request you've referenced, which has been tested in A.T.

**Comment by nickcolley** [comment]
Thanks for the additional testing, we're gonna try and release this today.

**Comment by adamsilverstein** [comment]
Hello @nickcolley do you know if this also resolves the issues I'm seeing in https://github.com/alphagov/accessible-autocomplete/pull/278?

**Comment by nickcolley** [comment]
Hey @adamsilverstein I don't think these fixes will have resolved your issue unfortunately.

**Comment by adamsilverstein** [comment]
@nickcolley Thanks for clarifying.  This work still might help in form what needs to change their as well.

**Pull request merged**
