### PR TITLE
Update integration tests to WebdriverIO v6

### PR DESCRIPTION
**Pull request by lfdebrux**
This PR bumps all WebdriverIO related packages to their latest versions, and fixes issues arising.

### Notes

- The integration tests now use the latest version of WebdriverIO v6
- The integration tests now use [W3C spec capabilities](https://w3c.github.io/webdriver/#capabilities), except for Internet Explorer 9
- The integration tests now build assets before running the tests using `npm run build`, as `wdio-webpack-dev-server-service` is no longer supported (#449)
- You can no longer use the envvar `SAUCE_CONNECT_VERSION` to choose the version of Sauce Connect Proxy when running the integration tests, as `@wdio/sauce-service` no longer uses the `sauce-connect-launcher`
- You can now find the verbose logs from the integration tests in the folder `logs/`

### CODE REVIEW

**Comment by hannalaakso** [comment]
It would be great if this PR could remove the temporary fix we added in https://github.com/alphagov/accessible-autocomplete/pull/451 to patch the issue.

**Comment by 36degrees** [comment]
Currently in a back-and-forth with SauceLabs support trying to unpick the issue with Internet Explorer 9.

> Hi,
> 
> Following on from a conversation with Christian Bromann in the webdriverio Gitter channel, he asked me to report this here.
> 
> We're having an issue with Sauce VMs failed to start IE9, seen whilst trying to upgrade from Webdriver 4.14.0 to 6.1.19 (it worked fine with Webdriver 4.14.0).
> 
> We're seeing "No matching capability sets found. Unable to match capability set 0: selenium:webdriver.remote.quietExceptions is an unknown extension capability for IE”.
> 
> An example of a failing test can be found here:
> https://app.saucelabs.com/tests/ad46729b54fa468e9a1cbe84c391914c#0
> 
> The same tests build fine against IE10 + IE11.
> 
> Our capabilities are defined here:
> https://github.com/alphagov/accessible-autocomplete/blob/248622378f554db986cd0d477070434df4af0752/test/wdio.config.js#L22-L62
> 
> Further details are in my colleague's commit here:
> https://github.com/alphagov/accessible-autocomplete/pull/450/commits/887013e3c561853dac072ec2a0ec87ba4ca09507

---

> Hello,
> 
> Thank you for contacting Sauce Labs support. Happy to investigate! Looking at your colleague's comments, I suspect he's correct that it's a combination of the IEdriver issue and that the session is being executed using W3C protocol. To use JWP, you can simply remove the "sauce:options" object and pass the legacy capabilities below as mentioned here
> 
> ```
> 'browserName': 'internet explorer',
> 'platform': 'Windows 7',
> 'version': '9.0',
> "tunnelIdentifier": {tunnelID}
> ```
>
> Additionally, we do have the following W3C documentation that can be a very helpful reference when updating tests to use W3C.
> 
> https://wiki.saucelabs.com/display/DOCS/W3C+Capabilities+Support#W3CCapabilitiesSupport-UpdatingWebDriverCapabilities
> 
> Please try the above capabilities and let us know if we can be of any additional assistance. 

---

> Hi,
> 
> Thanks so much for coming back to me.
> 
> I’ve tried removing the sauce:options object and passing legacy capabilities, like this:
> 
> ```
> [ { browserName: 'internet explorer',
>        build: undefined,
>        version: '9.0',
>        platform: 'Windows 7' } ]
> ```
> 
> However, SauceLabs still seems to be using the W3C protocol as we’re seeing this in the SauceLabs logs:
> 
> > Illegal key values seen in w3c capabilities: [platform, version]
> 
> Any ideas?

---

> Hello,
> 
> Thank you for following up. Is a test created in the Sauce Labs dashboard when that error is encountered? If so, would you be able to share the generated test? I suspect that the error is originating from the framework's configuration. Would you also be able to share the full test runner logs when this occurs? 
> 
> After researching, it seems similar to this reported webdriverio issue, https://github.com/webdriverio/webdriverio/issues/3743. Would you be able to check Christian's suggestions from his March 21 comment and verify that isn't causing the error? 

---

> Hi,
> 
> I’m not sure how, but from running the test once with just the one capability we seem to get 4 jobs created in SauceLabs (all of which fail):
> 
> https://app.saucelabs.com/tests/915df6eeb42b477daf71f515c6ff900a
> https://app.saucelabs.com/tests/33bbf79dbaec4dfbbe096382ce9f46c6
> https://app.saucelabs.com/tests/01588b3b6c104373ae2700bb130ba660
> https://app.saucelabs.com/tests/145ef66ebd194752b260e21b5142983b
> 
> The test runner logs with --logLevel trace look like this:
> 
> ```
> > cross-env NODE_ENV=test wdio test/wdio.config.js --logLevel trace
> 
> Execution of 1 spec files started at 2020-07-01T08:07:13.723Z
> 
> (node:93731) ExperimentalWarning: The dns.promises API is experimental
> (node:93731) ExperimentalWarning: The fs.promises API is experimental
> [0-0] (node:93744) ExperimentalWarning: The dns.promises API is experimental
> [0-0] (node:93744) ExperimentalWarning: The fs.promises API is experimental
> [0-0] { outputDir: './logs/',
>   specs: [ './test/integration/**/*.js' ],
>   capabilities:
>    [ { browserName: 'internet explorer',
>        build: undefined,
>        version: '9.0',
>        platform: 'Windows 7' } ],
>   baseUrl: 'http://localhost:4567',
>   screenshotPath: './screenshots/',
>   services: [ [ 'static-server', [Object] ], [ 'sauce', [Object] ] ],
>   reporters: [ 'spec' ],
>   framework: 'mocha',
>   mochaOpts: { timeout: 30000 },
>   user: 'tvararu-alphagov',
>   key: '[REDACTED]' }
> [0-0] RUNNING in internet explorer - /test/integration/index.js
> [0-0]  Error:  Failed to create session.
> Infrastructure Error -- The Sauce VMs failed to start the browser or device.
> For more info, please check https://wiki.saucelabs.com/display/DOCS/Common+Error+Messages
> [0-0] FAILED in internet explorer - /test/integration/index.js
> 
> Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:02:29
> ```
> 
> Our test config is structured to either create a services array of [’static-server’, 'selenium-standalone’] OR [’static-server’, ’sauce’] depending on whether SauceLabs is set up for the person running the tests – it should never include both. You can see in the config dump above that only [’static-server’, ’sauce’] are included. So I don’t think this is the problem suggested by Christian’s comment?
> 
> Thanks again for your help so far.

Waiting for a response to that last email at the minute.

**Comment by 36degrees** [comment]
@lfdebrux thanks very much for keeping this PR up to date 👍  Hopefully we'll be able to resolve the IE9 issue soon and get this merged.

**Comment by lfdebrux** [comment]
@36degrees no worries! Nice going talking to Sauce Labs, I hope it all gets sorted without using up too much more of your time!

**Comment by 36degrees** [comment]
Reply from SauceLabs:

> Hello Oliver, 
> 
> Thank you for following up. With the tests reaching Sauce Labs, I agree that Christian's comments are likely not the cause. 
> 
> Looking at the test, it appears that the issue is how the tunnelIdentifier capability is being sent in the test. Pictured below, you'll see in the test's base configuration that although you've removed sauce:options, the tunnelIdentifier is still being passed inside that object somehow, which causes the session to expect w3c. 
> 
> 
> Screenshot
> 
> From the provided configuration, I see that you are using the option below to use Sauce Connect. I'm currently not finding an option to prevent the tunnel from being sent this way, but plan testing it further on my end. We will be sure to update you with the results. 
> https://webdriver.io/docs/sauce-service.html
> 
> In the meantime, please let us know if you have any additional questions.

**Comment by lfdebrux** [comment]
> > From the provided configuration, I see that you are using the option below to use Sauce Connect. I'm currently not finding an option to prevent the tunnel from being sent this way, but plan testing it further on my end. We will be sure to update you with the results.

Ah of course, that'll be it. Unfortunately looking at the code there isn't a way I can see of stopping the tunnel identifier being in `sauce:options`. There was one but it was removed in commit https://github.com/webdriverio/webdriverio/commit/5c6672c72c2846067ccf74ed68ed8839cfea3c11#diff-17fd2062461d6ba99902a346af277ec5L32 but I guess we could raise a PR to reinstate it?

**Comment by 36degrees** [comment]
> Hello Oliver, 
> 
> Thank you for your patience. After further investigation, I was able to confirm that the Sauce Connect option inside of the sauce service package is causing the issue. There currently is not a way to use the the sauceConnect option with a browser that does not support W3C because of it's default behavior to pass the tunnelIdentifier inside of the sauce:options object. 
> 
> With that, please open an issue with the sauce-service dependency here regarding this behavior.
> 
> In the meantime, a workaround to test using Sauce Connect with older browsers would be to start the Sauce Connect client outside of wdio, and then include the configured tunnel identifier in the test's capabilities. The below article is a very helpful reference for configuring the SC client.
> 
> https://wiki.saucelabs.com/display/DOCS/Basic+Sauce+Connect+Proxy+Setup#BasicSauceConnectProxySetup-ValidatingYourBasicSauceConnectProxySetup
> 
> Please let us know if we can be of any additional assistance.

**Comment by lfdebrux** [comment]
A workaround for the issues with IE9 has been merged into WebdriverIO in webdriverio/webdriverio#5610. Once that has made it into a point release I will update this PR :)

**Comment by lfdebrux** [comment]
WebdriverIO v6.3.0 with https://github.com/webdriverio/webdriverio/pull/5610 has been released! 🎉 

The Sauce Labs tests now all work with WebdriverIO v6 🙂

**Comment by lfdebrux** [comment]
There was a bug in @wdio/sauce-service 6.3.0, fixed in [6.3.1](https://github.com/webdriverio/webdriverio/releases/tag/v6.3.1).

Maybe the tests will pass now...? 🤞

**Comment by lfdebrux** [comment]
The tests all passed, with IE9! 🎉 

However, there was some flakiness, I had to restart one of the Travis builds :/

**Comment by lfdebrux** [comment]
🎉

**Pull request merged**
