### PR TITLE
fix: selection and timeout race condition

### PR DESCRIPTION
**Pull request by tobias-g**
We noticed an intermittent issue where a user would select an item from the typeahead and instead of filling in the input with the value and closing the menu below the input value would not change and the menu remains open requiring the user to click again to make the selection.

This occurred more frequently on IE than other browsers though it did seem affect all browsers.

Some digging lead me to believe it was related to `pollInputElement`. Here's the steps that look like they are the cause of this race condition:

- User selects an item and this ends up calling `handleOptionClick`
- `handleOptionClick` updates the state to set the selected value and close the menu
- Here render should be called and the input value updated in the DOM and menu hidden however in some occurances... `getDirectInputChanges` is called via `pollInputElement` before render is called
- `getDirectInputChanges` grabs the value from the input (because render has yet to be called its not the selected value in the state)
- `handleInputChange` is called because state value and input value does not match
- Now the menu state is updated to be open and selected value in state is updated to input value
- Render gets called and user ends up seeing open menu and their selection not selected

My React know how is pretty green so input on whether this makes sense or the fix I suggest is not optimal let me know. Also really sorry but not sure on best way to unit test this fix. It may make the webdriver tests more stable though?

Fix I added was to forceUpdate to get render to call whenever `handleOptionClick` is called.

Cheers 🍺

### CODE REVIEW

**Comment by samtsai** [comment]
@tobias-g having similar issues but what's worse is it seems to happen all the time in certain parts of our app. Tested the areas with this PR and it's working great!

**Comment by danmitchell-** [comment]
Thanks for this @tobias-g, lets get #217 merged first and then we can look at this one and #226 👍

**Comment by tobias-g** [comment]
@danmitchell- rebased this one so good for you to take a look at now, thanks.

**Comment by samtsai** [comment]
Hi @tobias-g @danmitchell- can this one be moved forward again?

**Comment by danmitchell-** [comment]
@tobias-g @samtsai sorry guys, back on this now. Would you mind rebasing again @tobias-g and then i'll merge it?

**Comment by samtsai** [comment]
@tobias-g @danmitchell- I created a fork and PR of a rebased version with an additional "fix" see #238

**Comment by samtsai** [comment]
This can be closed now that #238 is merged, thanks @tobias-g for the actual work!

**Comment by danmitchell-** [comment]
Thanks for this guys!

**Comment by tobias-g** [comment]
Struggled to get time to rebase this so thanks @samtsai for getting it sorted :)

**Pull request closed without merging**
