### PR TITLE
Use innerText, not innerHTML, for select reading

### LINKED ISSUE #151: & (ampersand) in option becomes &amp; in the text input
To recreate:

enhance a select with an ampersand in an option:
```
<select>
    <option value="?organisations=hm-revenue-customs">HM Revenue & Customs (83389)</option>
</select>
```

When this is selected using the autocomplete it becomes &amp; in the text input

image

This happens whether the ampersand is escaped in the <option> (&amp;) or not

### PR DESCRIPTION
**Pull request by dracos**
Using innerHTML meant e.g. `&` was being shown as `&amp;` in selected items. It also meant you couldn't search for e.g. `&` then space, you had to search for `&amp;`. Switch to `textContent || innerText` (though I only put innerText in the commit message, who knows why).

Fixes #151.

### CODE REVIEW

**Comment by dracos** [comment]
Wasn't sure where best to add a test (or if just changing one of the country names in the wrapper.js test would have done :) ).

**Comment by dracos** [comment]
Tests added (one for hint, one for input after selection) :)

**Comment by tvararu** [comment]
Great work! 👍

**Comment by tvararu** [comment]
Published in `v1.4.1`!

**Pull request merged**
