### PR TITLE
Show all values 2 - show all values on click (like dropdown)

### PR DESCRIPTION
**Pull request by joelanman**
replaces #158 so we can get a PR app on heroku

### CODE REVIEW

**Comment by joelanman** [comment]
bug: pressing space does activate the dropdown, but only by accident as ' ' matches some options. Space (and down arrow?) should open the dropdown the same as a click does.

**Comment by joelanman** [comment]
I've added README update, and fixed className.

I've had a bash at handling space. Do you think it ought to be handled in `handleKeyDown` instead?

**Comment by joelanman** [comment]
I added code to trigger the dropdown on space and arrow down. I think this is ready to go.

One thing - visually, you get an indication you can view all values because it looks like a dropdown. How can we communicate that to screen reader users?

**Comment by joelanman** [comment]
@tvararu I've added the code you requested

**Comment by joelanman** [comment]
@tvararu ready to go I think

**Comment by carolinegreen** [comment]
@joelanman That's published now to version 1.4.0

**Comment by joelanman** [comment]
@carolinegreen thanks!

**Pull request merged**
