### PR TITLE
Remove pointer events check

### PR DESCRIPTION
**Pull request by nickcolley**
It's not clear to me why this functionality was added since the component does not use pointer events on the hint (https://github.com/alphagov/accessible-autocomplete/blob/master/src/autocomplete.css) so I'm attempting to remove it, and see if there's another way to resolve issues with IE9 that don't break CSP

> Don't display <Hint /> on browsers without pointer events (fixes IE9 tests)
https://github.com/alphagov/accessible-autocomplete/pull/101

I've tested the autoselect example in IE9 and it works as expected.

Related: https://github.com/alphagov/accessible-autocomplete/issues/398

### CODE REVIEW

**Comment by nickcolley** [comment]
Theo:

> yeap, if I recall correctly, IE9 does not overlap inputs nicely
> 
> the hint text is based on an overlayed input as you know (edited) 
> and it was misbehaving in IE9

Will do some more testing in IE9 and see if I can reproduce this.

**Comment by nickcolley** [comment]
Had another look at this, I think this is safe to remove for users of IE9 but it may be failing a Saucelabs test, worth checking once we've resolved the flakey saucelabs dashboard.

**Comment by hannalaakso** [comment]
This makes sense to me as since @nickcolley pointed out, it seems that the pointer events check was added to resolve failing tests, rather than fix IE9 itself (https://github.com/alphagov/accessible-autocomplete/pull/101#issue-119168009). So if the tests pass then it looks 👍

**Comment by nickcolley** [comment]
Will rebase and see if the tests pass.

**Comment by nickcolley** [comment]
@hannako needs an official approval :)

**Comment by hannako** [comment]
@hannako is me Jessica Jones, @hannalaakso is Hanna! Sorry for my weird username!!

**Comment by nickcolley** [comment]
Damnit sorry @hannako :(

**Pull request merged**
