### PR TITLE
Refinements to address accessibility issues

### PR DESCRIPTION
**Pull request by markhunter27**
The changes are focused on improvements in the following browser / screen reader combinations:

- Internet Explorer and JAWS
- Firefox and NVDA
- Safari and VoiceOver
- iOS Safari and VoiceOver 

..although we've also considered the NVDA and JAWS readers with each combination of Firefox, IE, and Chrome.

The changes are in part refinements to the markup of the component (type and placement of ARIA attributes), and in part changes to the detail and timing of ARIA live region updates ('status' updates in the terminology of the component).  

**Summary of refinements:** 

- Ensure immediate announcement of hint/status text when field receives focus..

      - Previously 'Select your country edit blank"
      - Now 'Select your country combobox collapsed editable blank. Type in 2 or more characters for results."

- On typing in a field with a 2 character minimum configuration (optional configuration)

      - Previously typing  'a' .. the typing echo reads 'a', and nothing else
      - Now reads 'a' .. then reads 'type in 2 or more characters for results'

- On finding no search results..

      - Previously, reads 'No search results dot' .. multiple times (up to 7 in NVDA)
      - Now, reads 'No search results' a single time, and nothing else.

- On finding search results

       - Previously typing a few characters e.g. 'as' .. reads '8 results are available' multiple times.
          Selecting one of the search results then reads "8 results are available, UK, 1 of 8 is selected dot" - multiple times                 
       - Now, reads '8 results are available' a single time
          Selecting one of the search results reads '8 results are available, UK, 1 of 8 is selected' once. (period removed)

- Form fields are now visible in overview (NVDA Insert + F7 , rotor in VoiceOver)

- (Related to the above) Form fields can now be selected directly using relevant form navigation key (e.g. key 'F' in NVDA)

- Generally - no longer reads 'comma' or 'dot' on aria announce

  (Refined the previous 'comma' approach  https://github.com/alphagov/accessible-autocomplete/issues/200#issuecomment-316755847
   Now using a pair of aria live regions and flip-flopping between to work around React virtual DOM behaviour, which can otherwise trigger repeated, duplicate announcements)

- Reduced overly verbose selection announce in JAWS on IE, by refining use of role=alert

- Simplified aria live region 'div' elements (removed inner span element). Improves situation in JAWS on IE where aria live content would not otherwise be announced without first disabling 'virtual PC cursor' mode (which is on by default).

- Introduced a general event debounce on status update (aria live region update). This delays and limits frequency of aria live updates, and has the following benefits:

       - Improves situation on Mac Safari / VoiceOver where typing echo can otherwise interrupt announcement of the aria live content.

       - Improves the rapid typing situation in IE + JAWS, where fast user input can sometimes fail to trigger announcement.

       - Improves a situation in NVDA where stale results are sometimes announced. 
          e.g. when arriving at an initial result list and then filtering further by typing more characters, a situation can arise where the screen reader announces stale count information, e.g.
          '8 results are available, UK, 1 of 8 is selected' ..then ..
          'UK, 1 of 23'
          ..where the '23' relates to the size of initial result list.

### CODE REVIEW

**Comment by markhunter27** [comment]
Will re-open PR after our DAC evaluation and any other refinements or recommends that result :)

**Comment by nickcolley** [comment]
@markhunter27 thanks a lot Mark, we appreciate it!

**Comment by markhunter27** [comment]
Hi @nickcolley , I'm about to reopen  / recreate this PR. Would you prefer I squash my commits down into just three or four, with summarising comments within?

If you'd like to discuss before I raise another PR -  feel free to give me a shout.
You can hit the amended version with the latest set of changes [here](https://markhunter27.github.io/accessible-autocomplete/examples/form-single.html)
Thanks :)

**Comment by markhunter27** [comment]
Hi @nickcolley 
DAC have responded positively to our latest changes, so I've created a new PR. Unfortunately I can't re-open this one as I've since done some git rebase to tidy some of my commit history - sorry about that :)
There are a few extra changes in the new PR - a few extra refinements that were the result of further, more detailed testing, and from the DAC feedback.

**Pull request closed without merging**
