### PR TITLE
firefox 45 'down-down' bugfix

### PR DESCRIPTION
**Pull request by revilossor**
this fixes an issue we have been experiencing in firefox 45 - when the user pressed down twice, the menu closes and the selected option is chosen. This is related to 'relatedTarget' for blur events always being null in firefox.

### CODE REVIEW

**Comment by revilossor** [comment]
@tvararu ping?

**Comment by tvararu** [comment]
Hey @revilossor I'm not in GDS anymore so can't merge this, sorry! @nickcolley @alex-ju do you know who may be able to review/merge this or other PRs?

**Comment by revilossor** [comment]
@nickcolley @alex-ju any ideas who owns this repo ( and [openregister location picker](https://github.com/alphagov/govuk-country-and-territory-autocomplete) )? I need a bugfix to be merged.

**Comment by edwardhorsford** [comment]
Paging @danmitchell @carolinegreen.

**Comment by danmitchell-** [comment]
I don't have permission to merge this @edwardhorsford. I think @36degrees does though

**Comment by revilossor** [comment]
thank you @danmitchell-

**Pull request merged**
