### PR TITLE
Disable hint

### LINKED ISSUE #120: Add option to disable `<Hint />`
We provide options for most other features, so maybe we should for this as well if people request it.

### PR DESCRIPTION
**Pull request by carolinegreen**
Allow users to hide the hint when using autoselect.  Closes #120.

With hint:

screen shot 2017-07-07 at 14 41 06 1

Without:

screen shot 2017-07-07 at 14 41 21

### CODE REVIEW

**Comment by edwardhorsford** [comment]
Can you include before and after screenshots?

**Comment by carolinegreen** [comment]
@edwardhorsford Yes good point.

**Comment by tvararu** [comment]
Should update this with some tests.

**Comment by tvararu** [comment]
The tests are failing because [IE9 doesn't have pointer events](http://caniuse.com/#search=pointer%20events); we need to wrap the tests to only run if `isIE9` (the variable is already declared but commented at the top of the tests).

**Comment by tlwr** [comment]
I'm closing this PR as it has been open for a considerable amount of time and we're trying to cut down the number of orphaned PRs in alphagov.

**Pull request closed without merging**
